#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
inkscape-figures watch 
python ~/inkscape-shortcut-manager/main.py &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Inkscape desktop='next.!occupied' follow=on
bspc rule -a Zathura state=tiled
#bspc config external_rules_command ~/.config/bspwm/external_rules

wid=$1
class=$2
instance=$3


if [ "$instance" = "popup-bottom-center" ]; then
    echo "state=floating"
    read W H <<< $(xdotool getdisplaygeometry)
    eval "$(xdotool getwindowgeometry --shell $wid )"
    xdotool windowmove $wid $(($W / 2 - $WIDTH / 2)) $(($H - $HEIGHT))
fi
